### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by SoftMaker** [epsagon/serverless-plugin-epsagon#12]
Hello!

I tried to use Your serverless plugin, but after successful sls deploy command I try to invoke lambda and the result is:

```
{
  "errorMessage": "Cannot find module '/var/task/epsagon_handlers/cronLauncher-epsagon'",
  "errorType": "Error",
  "stackTrace": [
    "require (internal/module.js:11:18)"
  ]
}
```

I'm using serverless with webpack plugin and middy [middy](https://github.com/middyjs/middy).

OS: Ubuntu 18.04
Node version: 10.10
Serverless framework version: 1.32.0

**Comment by galbash** [comment]
Hey @SoftMaker , Thanks for taking the time for submitting an issue! I will try to reproduce and fix it, but in the meantime can you package your project (`sls package`, doesn't have to be your project - can be any sample project the issue reproduces in) and upload it for me to examine?

Thanks!

**Comment by galbash** [comment]
Hey @SoftMaker , I am going to go ahead and close this issue as resolved. If this is not the case - please reply here so it will be reopened.
