### ISSUE TITLE
Error: Can't resolve 'aws-sdk' in ... epsagon/dist'

### ISSUE THREAD

**Issue by KalSadaram** [epsagon/serverless-plugin-epsagon#21]
Hi,

I have a lambda function that returns a string. We are using serverless framework for build and distribution. We are getting below error when we run serverless webpack

ERROR in ./node_modules/epsagon/dist/bundle.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/Documents/02. Projects/aws/newproj/packages/backend/dt_aws/node_modules/epsagon/dist'
 @ ./node_modules/epsagon/dist/bundle.js 1:428-446
 @ ./epsogan.ts
 @ ./func/hellofunc.ts
 @ multi ./func/hellofunc.ts

If I understand above error correctly webpack is trying to find aws-sdk to bundle and failing because it cannot find it. If this is true then do we need to add aws-sdk to dev dependency? 

Thanks,

Kal

**Comment by ranrib** [comment]
Hi @KalSadaram, please update package to 1.6.1. Thanks!
