### ISSUE TITLE
The AWS CloudWatch Log Group Subscription filter still be added if disabling Epsagon function at a function level 

### ISSUE THREAD

**Issue by kunhuangau** [epsagon/serverless-plugin-epsagon#62]
The service level Epsagon is enabled as below:
_custom:
    epsagon:
        disable: false_

One of the function disabled the Epsagon in function level, but the AWS Cloudwatch Log Group subscription filter still be added for this function. Can we make the subscription filter be added only Epsagon Enabled? Thanks

**Comment by ranrib** [comment]
Hi @kunhuangau, the traces and subscription are two different things, managed by different services in Epsagon. We can talk more about how you can stream logs into 2 places or disable it for a specific function.
