### ISSUE TITLE
Supported NodeJS runtimes

### ISSUE THREAD

**Issue by ColdFire87** [epsagon/serverless-plugin-epsagon#78]
Hi, I'm getting these messages during packaging after updating from `1.7.1` to `1.8.0`:

![image](https://user-images.githubusercontent.com/14059086/84029647-a65e4b80-a98a-11ea-95ec-02d55c90a618.png)

Reverting back to `1.7.1`, the issue goes away.

Also, out of curiosity, what are the NodeJS runtimes that the serverless plugin & nodejs tracer library support?

Thanks!

**Comment by ranrib** [comment]
Hi @ColdFire87 ! thanks for reporting, we're on it. 
Today we support Node8, 10, and 12.

**Comment by ranrib** [comment]
A version (1.8.1) will be released soon - it will publish a message on the PRs page
