### ISSUE TITLE
Unable to set "ignoredKeys" from serverless.yml

### ISSUE THREAD

**Issue by brigitte0** [epsagon/serverless-plugin-epsagon#89]
Hi, I tried to set "ignoredKeys" in serverless.yml but I couldn't get it to work. I glanced at the generated epsagon_handlers code and I could see that `process.env.EPSAGON_IGNORED_KEYS` assigned with the correct value. However, during runtime in lambda `process.env.EPSAGON_IGNORED_KEYS` is undefined.

I'm on `1.10.0` and using typescript on node 12.

**Comment by enoodle** [comment]
@brigitte0 Hi,
Can you share an example of how you set the "ignoredKeys" value in your serverless.yml?

**Comment by enoodle** [comment]
Fixed by: #91 

The environment variables were set after epsagon already tried to read them, so they were not effective.
